name: build game
on: [push, pull_request]

jobs:
  build-android:
    runs-on: macos-latest
    steps:
      - run: curl -Lv -o /tmp/bundletool.jar https://github.com/google/bundletool/releases/download/1.18.3/bundletool-all-1.18.3.jar
      - run: |
          echo "ANDROID_NDK_PREBUILT_ROOT=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/darwin-x86_64" >> "$GITHUB_ENV"
          echo "ANDROID_BUILD_TOOLS=$ANDROID_SDK_ROOT/build-tools/37.0.0" >> "$GITHUB_ENV"
          echo "ANDROID_PLATFORM=$ANDROID_SDK_ROOT/platforms/android-37.0" >> "$GITHUB_ENV"
          echo "ANDROID_BUILDBUNDLE=/tmp/bundletool.jar" >> "$GITHUB_ENV"
      - run: brew install glslang
      - uses: actions/checkout@v6
        with:
          submodules: true
      - run: clang -o build build-droid.c
      - run: ./build
  build-ios:
    runs-on: macos-latest
    env:
      IOS_BUILD_ONLY: yup # Just run a build check
      IOS_TEAM: dummy
      IOS_SIGN_ID: "dummy Certificate Name"
      IOS_BUNDLE_ID: com.github.m4c0.example
      IOS_PROV_PROF: "dummy Development"
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - run: brew install glslang
      - run: curl -L -o moltenvk.tar https://github.com/KhronosGroup/MoltenVK/releases/download/v1.4.2/MoltenVK-ios.tar
      - run: tar xfv moltenvk.tar
      - run: mv MoltenVK/MoltenVK/static/MoltenVK.xcframework/ .
      - run: clang -o build build-ios.c
      - run: ./build
  build-osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - run: brew install glslang
      - run: curl -L -o moltenvk.tar https://github.com/KhronosGroup/MoltenVK/releases/download/v1.4.2/MoltenVK-macos.tar
      - run: tar xfv moltenvk.tar
      - run: mv MoltenVK/MoltenVK/static/MoltenVK.xcframework/ .
      - run: touch libvulkan.dylib # hack
      - run: clang -o build build-osx.c
      - run: ./build
  build-windows:
    runs-on: windows-latest
    steps:
      - run: dir 'c:\Program Files (x86)\Windows Kits\10\bin'
      - uses: actions/checkout@v6
        with:
          submodules: true
      - run: curl -L -o glslang.zip https://github.com/KhronosGroup/glslang/releases/download/main-tot/glslang-main-windows-x86_64-release.zip
      - run: unzip glslang.zip bin/glslang.exe
      - run: mv bin/glslang.exe .
      - run: clang -o build.exe build-win.c
      - run: ./build.exe
      - uses: actions/upload-artifact@v7
        with:
          name: windows-exe
          path: boas.exe
      - shell: pwsh
        run: |
          $env:Path += ";c:\Program Files (x86)\Windows Kits\10\bin\10.0.26100.0\x64"
          makeappx.exe pack /f AppxMapping.ini /p boas.msix
      - uses: actions/upload-artifact@v7
        with:
          name: windows-msix
          path: boas.msix

